### ISSUE TITLE
Player names are not updating

### ISSUE THREAD

**Issue by makarasty** [Kieaer/Essentials#139]
The player's name reverts to the old one until I update it in MySQL.
![image](https://github.com/user-attachments/assets/e0d85601-65e3-4de6-a65a-499ade2b3e5e)
![image](https://github.com/user-attachments/assets/92c78493-f241-48be-b10b-2c14ccbc9fb5)
The screenshots show a single player

**Comment by Kieaer** [comment]
``strict: false`` in config_protect.yaml
https://github.com/Kieaer/Essentials/blob/main/EssentialProtect/src/main/java/essential/protect/Event.java#L153

**Comment by makarasty** [comment]
But it is already set to the value `false`
![image](https://github.com/user-attachments/assets/de8bcc14-d907-44b6-84d0-6d7255f34505)

**Comment by makarasty** [comment]
Here is my configuration
```yaml
pvp:
  peace:
    # Sets it so that no damage can be inflicted for a certain period of time immediately after starting PvP. (default: false)
    enabled: false

    # Time unit is seconds (default: 300)
    time: 300

  border:
    # If a unit leaves the world border, it is destroyed. (default: false)
    enabled: false

  # If the team loses, all buildings are destroyed. (default: false)
  destroyCore: false

account:
  # If this feature is enabled, players will need to log in to account using the auth-type value to play. (default: false)
  enabled: false

  # Available method: password, discord
  authType: "password"

  # If you set auth-type to discord, you can enter the discord invite link below to be directed to this discord address.
  discordURL: ""

protect:
  # Ensures the core is never destroyed. (default: false)
  # This is useful in certain game modes or lobby servers.
  unbreakableCore: false

  # If a large amount of power supply is lost due to power node disconnection, a message is notified. (default: true)
  powerDetect: true

rules:
  # Block datacenter IP
  vpn: false

  # Block foo's client
  foo: false

  # Allow mobile users to access the server.
  mobile: true

  # Blocks access to all users except Steam users.
  steamOnly: false

  # Set nickname minimal length
  minimalName:
    enabled: false
    length: 4

  # Prevent players from changing their nicknames. (default: false)
  # This is useful for catching people who change their nicknames frequently and are grieving.
  strict: false

  # When attacked by an external program or modded client, you can protect the server and existing users by activating this setting.
  blockNewUser: false
  ```
