### ISSUE TITLE
The `/vote y` command does not work

### ISSUE THREAD

**Issue by makarasty** [Kieaer/Essentials#140]
Due to the plugin overwriting the `vote` command, players are unable to initiate a basic vote to kick in Mindustry. Additionally, even if a player somehow manages to start a basic vote to kick, other players cannot use `/vote y` to gather the required number of votes.
![image](https://github.com/user-attachments/assets/816e9e90-a9a4-40c1-a4e8-478911007982)
```yml
  vote:
    # Use plugin voting system (default: true)
    enabled: true
    # If you use this feature, players can be start voting from player list.
    # A modded client may start voting for random players and then watch them griefing.
    enableVotekick: true
```
![image](https://github.com/user-attachments/assets/4a8e6160-4dbb-4f5d-b7fd-cfc99b48c744)
```yml
  vote:
    # Use plugin voting system (default: true)
    enabled: false
    # If you use this feature, players can be start voting from player list.
    # A modded client may start voting for random players and then watch them griefing.
    enableVotekick: true
```
logs
```
 [01-16-2025 15:09:46] [I] Randomized next map to be Normal Ocean.
[01-16-2025 15:09:46] [I] Loading map...
[01-16-2025 15:09:46] [I] Map loaded.
[01-16-2025 15:09:46] [I] Opened a server on port 27715.
[01-16-2025 15:09:50] [I]  MaKarastY has connected. [pU6gLelVSFQAAAAAJlBw9w==]
[01-16-2025 15:09:50] [I] Autosaving...
[01-16-2025 15:09:50] [I] Autosave completed.
[01-16-2025 15:09:50] [I] chromidum has connected. [RTcb/rAmtFYAAAAA1J1/7Q==]
[01-16-2025 15:10:01] [I] charmiz has connected. [otiDke2ZhAQAAAAA73GZoA==]
[01-16-2025 15:10:05] [I] < MaKarastY: /votekick #1316 1>
[01-16-2025 15:10:16] [I] BUR has connected. [dTHt23U7UkMAAAAAyP7dTA==]
[01-16-2025 15:10:26] [I] <BUR: /votekick #1315 frtf>
[01-16-2025 15:10:32] [I] BUR: nema
[01-16-2025 15:10:40] [I] <BUR: /votekick #1315 votekick lol>
```
